function [S, ST] = rk_struct(A, B)
%BUILD_RK_STRUCT Build a struct for building rational Krylov subspaces. 
%

if ~exist('B', 'var')
    B = eye(size(A), 'like', A);
end

S = struct(...
            'solve', @(nu, mu, x) (nu * A - mu * B) \ x, ...
            'multiply', @(rho, eta, x) rho * (A * x) - eta * (B * x), ...
            'isreal', isreal(A) && isreal(B), ...
            'nrm', normest(A, 1e-2));

ST = struct(...
            'solve', @(nu, mu, x) (nu * A' - mu * B') \ x, ...
            'multiply', @(rho, eta, x) rho * (A' * x) - eta * (B' * x), ...
            'isreal', S.isreal, ...
            'nrm', S.nrm);

end

