function html_file = CompileGuide
%COMPILEGUIDE Compile the toolbox guide from .m files.

if exist('stylesheet.xsl', 'file')
    publish_cmd = @(file) publish(file, 'stylesheet', 'stylesheet.xsl');
else
    publish_cmd = @(file) publish(file);
end

doc_files = { ...
    'QTDefinition.m', ...
    'Arithmetic.m', ...
    'LinearSystems.m', ...
    'JacksonExample.m', ...
    'SquareRoot.m', ...
    'QuadraticExample.m', ...
    'commands.m', ...
    'cmd_cond.m', ...
    'cmd_conj.m', ...
    'cmd_correction.m', ...
    'cmd_cqtinfo.m', ...
    'cmd_cqt.m', ...
    'cmd_cqtoption.m', ...
    'cmd_cqtrank.m', ...
    'cmd_ctranspose.m', ...
    'cmd_diag.m', ...
    'cmd_eye.m', ...
    'cmd_full.m', ...
    'cmd_inv.m', ...
    'cmd_limit.m', ...
    'cmd_normest.m', ...
    'cmd_size.m', ...
    'cmd_symbol.m', ...
    'cmd_transpose.m', ...
    'cmd_ul.m', ...
    'doc_eig.m'
};

main_file = 'index.m';

for i = 1 : length(doc_files)
    publish_cmd(doc_files{i});
end

html_file = publish_cmd(main_file);

if exist('numpi.css', 'file')
    copyfile('numpi.css', 'html/numpi.css');
end


end

